default_context:
    repo_name: "advance_pip_repo"
    project_name: "project_name"
    project_structure: "advance"
    deps_manager: "pip"
    add_coding_agent_support: true
    author_name: "author_name"
    description: "description"
    python_version: "3.12"
    open_source_license: "MIT"
